---
name: Run nix build on repo.
run-name: Build on `${{ forgejo.ref }}` by @${{ forgejo.actor }}.
on:
  push:

jobs:
  Build:
    runs-on: forgejo-latest
    container:
      credentials:
        username: luca
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - run: |-
          OUT="$(nix build --no-link --print-out-paths .#)"
          REFS="$(nix-store --query --references $OUT)"
          nix store sign --recursive --key-file /root/nix-store-key $OUT $REFS
          nix copy --to 'ssh-ng://nix-ssh@store.impure.systems:22023' $OUT $REFS
